### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by tjulises** [rodgars/bigball#27]
Hi @rodgars  ,
My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (open source) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by rodgars** [comment]
Hi @tjulises ,
Thank you very much for the logo proposal.
However we can't afford this.

Cheers,
Rodrigo Garcia

**Comment by tjulises** [comment]
I understand @rodgars ,
I'm an open source enthusiast looking forward to improve my portfolio, 
therefore, my collaboration will be totally _free_. 
let me know if you're interested, we could start working inmediately!

Cheers.

**Comment by rodgars** [comment]
Hi @tjulises ,
Wellcome a board!!!!! So, we have two logos we could replace, in our navbar and another in landing page.
You can get the images (bola.png and logo1.png) sizes in folder: client/public/assets/

Have a look in our current pages:

![bolao1](https://user-images.githubusercontent.com/20528688/41292080-de038852-6e27-11e8-8e47-025efa9664ed.png)

![bolao0](https://user-images.githubusercontent.com/20528688/41292086-e2a39118-6e27-11e8-981b-20c0129b68b3.png)
